### PR TITLE
Migrate to Swift 3

### PR DESCRIPTION
**Pull request by candostdagdeviren**
This PR includes migration of library and sample project to Swift 3.

### CODE REVIEW

**Comment by cjwirth** [comment]
Thanks! 

But I wanted to make some API changes, so I have a PR open at https://github.com/cjwirth/RichEditorView/pull/89 and a `swift-3` branch.

**Comment by candostdagdeviren** [comment]
If you added something like to-do list for Swift 3 transition, I would help that. For now, I don't know what is missing or what do you have in mind for Swift 3 transition.

**Comment by cjwirth** [comment]
Thanks!

I'm sorry I've been super lazy, but really the only thing left is figuring out which versions are compatible with semantic versioning. 

## Hard Way

Do I have things to release on 3.2.0 in the Swift 2 version? --> Release it as either 3.2.1 or 3.3.0 depending on what the changes are
Does the 2.3 branch build with Xcode 7? --> Release 2.3 as 3.3.0 (or 3.4.0, if I chose 3.3.0 in the previous step)
Does 2.3 break projects built with older versions? --> Release it as 4.0.0
Finally, release the Swift 3 version as either 4.0.0 or 5.0.0 based on what the previous version was.

## Easy Way

Forget about any lower version, and just release the Swift 3 version as 4.0.0 and be done with it. I think I already made all the API changes I wanted to make (I think...)

**Comment by candostdagdeviren** [comment]
Does 2.3 break projects built with older versions?
For this question, most probably I don't see a point to make it 4.0.0. First, it shouldn't break. Second, even if it breaks, you should release it as 3.3 or 3.4. Swift 3 implementation is a really big change in here. So only it should be released as major release.

**Comment by cjwirth** [comment]
> Does 2.3 break projects built with older versions?

Unlikely, but at this point I don't remember if I made any breaking changes to it or not.

> For this question, most probably I don't see a point to make it 4.0.0. First, it shouldn't break. Second, even if it breaks, you should release it as 3.3 or 3.4. Swift 3 implementation is a really big change in here. So only it should be released as major release.

I'm just trying to follow my understanding of [semantic versioning](http://semver.org/). If it's a breaking change, no matter how small, if upgrading to the new version will break your current build, it should be a major version update.

Now, I don't expect too many people to be using Swift 2.3, so I'd be OK just releasing Swift 3 version as 4.0.0 and keeping the Swift 2.3 version as a branch (unreleased)

**Comment by cjwirth** [comment]
I guess I should also note that I originally made this with CocoaPods as the main integration method, which is also the one the sample project uses. So when I say "release," I mean both making a tag, as well as pushing a version to the CocoaPods pod repo.

**Comment by candostdagdeviren** [comment]
If you don't remember that you did breaking changes for Swift 2.3, leave it on the branch for a while. If anybody wants to use it, they can use it from the branch. And release the Swift 3 as 4.0.0.

**Pull request closed without merging**
