### PR TITLE
Fix project compile error. Make Delegate methods all optional so you don't have to implement them all if you only want to make use of one.

### PR DESCRIPTION
**Pull request by ryanmaxwell**
A couple of fixes and improvements.

### CODE REVIEW

**Comment by cjwirth** [comment]
> Fix toolbar delegate method name

Darn! I can't believe I didn't notice this one....

It looks like some of these will be breaking changes (eg. forcing protocols to be NSObjects, changing delegate method name...). I wasn't really thinking about releasing a 3.0.0 for a while... But I guess if I want to have ObjC support as well, it's probably necessary...

**Comment by ryanmaxwell** [comment]
I don't think the NSObjectProtocol inheritance will be breaking - the protocols were already marked @objc (which buys us the ability to make the methods optional), and as this project won't be used outside of UIKit projects (it's built out of UIViews!) then I would say it's fine to follow UIKit convention and conform to NSObjectProtocol.

**Comment by cjwirth** [comment]
> I don't think the NSObjectProtocol inheritance will be breaking

It is breaking. 

```Swift
@objc protocol Jammable: class {
    optional func thisIsMyJam()
}

class Dancer: Jammable {
    @objc func thisIsMyJam() {
        print("Pump up the jam")
    }
}
```
This will work, but

```Swift
@objc protocol Jammable: NSObjectProtocol {
    optional func thisIsMyJam()
}

class Dancer: Jammable {
    @objc func thisIsMyJam() {
        print("Pump up the jam")
    }
}
```
will fail to build unless you change Dancer to subclass NSObject. 

> this project won't be used outside of UIKit projects (it's built out of UIViews!) then I would say it's fine to follow UIKit convention and conform to NSObjectProtocol.

You're right, it won't be used outside of UIKit and UIViews. I don't know if I would say that the UIKit protocols requiring NSObjectProtocol is a convention. I'd say it's more just legacy support for Objective-C. My RichEditorDelegates in my project are plain Swift classes, not NSObjects.

I'm not terribly opposed to it, but it _is_ a breaking change, and one that just seems unnecessary. I think making the methods optional is good though.

**Comment by cjwirth** [comment]
I've merged this into the development branch. I'm still waiting for someone to make some changes, so once I get that pull request, I'll merge everything and make a new release.

**Comment by cjwirth** [comment]
Got it in now :+1:

**Comment by ryanmaxwell** [comment]
Cheers. I've been adding blockquote support for a project i'm needing it for, i'll try tidy that up and submit a PR for you in the future for that too.

**Comment by cjwirth** [comment]
Ok that would be great! 

We added blockquote and list support in our app, too. There was a lot of weirdness, especially with things nested inside each other. The logic got pretty complicated, and too specific to our app, so I never added it to this repo.

**Comment by ryanmaxwell** [comment]
@cjwirth yep I'm facing the same issues, I may be able to extract it to be useful for everyone.

**Pull request merged**
