### PR TITLE
Swift 3

### PR DESCRIPTION
**Pull request by Kvamsikrishna**
Xcode 8, its not working in swift 3.0

### CODE REVIEW

**Comment by cjwirth** [comment]
What do you mean it's not working? It should work if you specify the `swift-3` branch to build from.
I still want to figure out some things about versioning before releasing the swift 3 version, but it should work from that branch.

**Comment by jumtop** [comment]
build failed, the xcode shows 7 errors, did you forget to commit some file, like Category for String and UIColor

**Comment by imclaren** [comment]
Yes, for some reason, when you manually download the swift-3 branch as a zip file, the following files are not included:
/RichEditorView/Classes/String+Extensions.swift
/RichEditorView/Classes/UIColor+Extensions.swift

The project runs when you manually download and include these files in the project.

**Comment by cjwirth** [comment]
> include these files in the project.

Thanks for this bit of information! I didn't realize that the people who were failing were actually trying to build the actual project itself 😖 

I just pushed a fix that should work. The `swift-3` branch should work again.

**Comment by sprynmr** [comment]
How is swift 3 looking as far as a cocoapods release?

**Pull request merged**
