### PR TITLE
Keep cursor always visible when typing.

### PR DESCRIPTION
**Pull request by idealx**

### CODE REVIEW

**Comment by cjwirth** [comment]
Hey, thanks! Good on you for looking into this.

However, it looks like you've run into the same problem that I ran into:
toolbar3

When you are on a line that has already scrolled, the _first_ character you type in will result in some weird animation. I've looked into this a bit before, and for some reason when you make a newline at that point, the size of the content (from JS inside the webview) get small for some reason.

This is a problem I'd want to fix before merging it ><

**Comment by Abdama** [comment]
This wouldn't work anyway. Type as much as you want such that the text overflows and scrolling is required. Now, try to type on the first line. You'll see you keep getting pushed down. I think there is a better way, hold up...

**Comment by cjwirth** [comment]
In my own project, we just keep on growing it (as opposed to scrolling). But it is in a `UIScrollView`, and so we _do_ need to keep track of where the cursor is, in order to reposition the cursor to be on screen.

[This](https://gist.github.com/anonymous/11cad790b1ea981fd61b) is the code we used to get the current cursor coordinates from JS. It will return a string like `4,270` in `x,y` format. That's supposed to be the current cursor's coordinates within the `UIWebView`. When the text changes, we check the coordinates, test if we have are still onscreen, and scroll until the cursor is visible.

It's been working for us so far, but its about 50 extra lines of code that may or may not be useful to the library, so I kept it separate, but maybe it could help out here too?

**Comment by Abdama** [comment]
implemented it in a similar way, just not using the selection function you use. I tried yours but it didn't work for me. Anyways, I get the caretY position relative to the scroll view (I don't know if that's the same with you). So for fontsize I use, any caretY < 5 is hiding the line/caret (caret is furthur UP). And any caret > frameHeight - 14 is also hiding the line/caret (caret is DOWN). Seems to work, but seems a bit too specific to my use-case with the constants and all.

**Comment by cjwirth** [comment]
Yeah, my function is getting the cursor location based on what is inside the web view, so it's probably more based on the `UIScrollView`'s bounds rather than the `UIWebView` itself. 

What I am using in my project is probably too specific too (I have the line `let cursorHeight = 30` in there, lol).

It'd be really nice if there was a really nice, general solution for this. I wonder if it would work to, instead of having a constant cursorHeight, to see if you could add the `lineHeight` or something to it?

**Comment by cjwirth** [comment]
Closing because it doesn't completely solve the problem, and there is an [issue](https://github.com/cjwirth/RichEditorView/issues/3) for it as well.

**Pull request closed without merging**
